### ISSUE TITLE
Allow icon sizing with CSS [FEAT]

### ISSUE THREAD

**Issue by Flob10** [iconoir-icons/iconoir#218]
With the provided CSS file, it is not possible to change icon size with properties _width_ or _height_. This is because these properties are directly defined in the svg paths (width="24" height="24").

Removing _width_ and _height_ from path and changing the following properties in the CSS file would allow to manage icons size directly with additional CSS : 

```css
*[class^="iconoir-"]::before,
 *[class*=" iconoir-"]::before {
   content: " ";
   display: block;
   background: currentColor;
   mask-size: cover;
   -webkit-mask-size: cover;
   width: 100%;
   height: 100%;
   min-width: 24px;
   min-height: 24px;
 }
 *[class^="iconoir-"],
 *[class*=" iconoir-"] {
   display: inline-block;
 }
```

The default icon size is still 24px but can be managed in the project CSS rules.
Hope you could find this useful.
